In [1]:
#import necessary file
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression, LogisticRegression,Ridge, Lasso
from sklearn import metrics
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier,DecisionTreeRegressor
from sklearn.model_selection import train_test_split,KFold, StratifiedKFold,cross_val_score, KFold,GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score,mean_squared_error
from sklearn.ensemble import RandomForestRegressor,RandomForestClassifier
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt




In [ ]:
drop_out = pd.read_csv("cleaned_drop_out.csv")
# drop_out.info()

In [ ]:
#create X and y

X = drop_out.drop(columns="Drop_Out")
y = drop_out["Drop_Out"]
# print(X)
# print(y)

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, stratify=y, random_state=42)
#knn
knn = KNeighborsClassifier(n_neighbors=6)
knn.fit(X_train,y_train)
y_pred_knn = knn.predict(X_test)
print("KNN Model")
print(accuracy_score(y_test,y_pred_knn))
print(confusion_matrix(y_test,y_pred_knn))
print(classification_report(y_test,y_pred_knn))


#decision tree
dt = DecisionTreeClassifier(max_depth=6,random_state=42)
dt.fit(X_train,y_train)
y_pred_dt=dt.predict(X_test)
print("Decision Tree Model")
print(accuracy_score(y_test,y_pred_dt))
print(confusion_matrix(y_test,y_pred_dt))
print(classification_report(y_test,y_pred_dt))

#logical 
logreg = LogisticRegression()
logreg.fit(X_train,y_train)
y_pred_logreg = logreg.predict(X_test)
print("Logical Regression")
print(accuracy_score(y_test,y_pred_logreg))
print(confusion_matrix(y_test,y_pred_logreg))
print(classification_report(y_test,y_pred_logreg))


#random forest
rf = RandomForestClassifier(n_estimators = 25,random_state=42)
rf.fit(X_train,y_train)
y_pred_rf=rf.predict(X_test)
print("Random Forest Classifier")
print(accuracy_score(y_test,y_pred_rf))
print(confusion_matrix(y_test,y_pred_rf))
print(classification_report(y_test,y_pred_rf))

KNN Model
0.8
[[24  0]
 [ 6  0]]
              precision    recall  f1-score   support

           0       0.80      1.00      0.89        24
           1       0.00      0.00      0.00         6

    accuracy                           0.80        30
   macro avg       0.40      0.50      0.44        30
weighted avg       0.64      0.80      0.71        30

Decision Tree Model
0.7333333333333333
[[21  3]
 [ 5  1]]
              precision    recall  f1-score   support

           0       0.81      0.88      0.84        24
           1       0.25      0.17      0.20         6

    accuracy                           0.73        30
   macro avg       0.53      0.52      0.52        30
weighted avg       0.70      0.73      0.71        30

Logical Regression
0.7333333333333333
[[22  2]
 [ 6  0]]
              precision    recall  f1-score   support

           0       0.79      0.92      0.85        24
           1       0.00      0.00      0.00         6

    accuracy                      

C:\Users\khiny\anaconda3\envs\project1\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\khiny\anaconda3\envs\project1\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\khiny\anaconda3\envs\project1\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result)

Random Forest Classifier
0.7666666666666667
[[23  1]
 [ 6  0]]
              precision    recall  f1-score   support

           0       0.79      0.96      0.87        24
           1       0.00      0.00      0.00         6

    accuracy                           0.77        30
   macro avg       0.40      0.48      0.43        30
weighted avg       0.63      0.77      0.69        30



In [5]:
print("Unique classes in y_train:", np.unique(y_train))

print("Class distribution in y_train:", np.unique(y_train, return_counts=True))
print("Class distribution in y_test:", np.unique(y_test, return_counts=True))

Unique classes in y_train: [0 1]
Class distribution in y_train: (array([0, 1], dtype=int64), array([56, 14], dtype=int64))
Class distribution in y_test: (array([0, 1], dtype=int64), array([24,  6], dtype=int64))


In [6]:
#baased with resample SMOTE
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scale = scaler.fit_transform(X_train_resampled)
X_test_scale = scaler.transform(X_test)

print(X_train_scale.shape)
print(y_train_resampled.shape)

(112, 53)
(112,)


C:\Users\khiny\anaconda3\envs\project1\lib\site-packages\sklearn\base.py:474: FutureWarning: `BaseEstimator._validate_data` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation.validate_data` instead. This function becomes public and is part of the scikit-learn developer API.
  warnings.warn(


In [7]:
#baased with resample SMOTE


#knn
knn = KNeighborsClassifier(n_neighbors=6)
knn.fit(X_train_scale,y_train_resampled)
y_pred_knn = knn.predict(X_test_scale)
print("KNN Model")
print(accuracy_score(y_test,y_pred_knn))
print(confusion_matrix(y_test,y_pred_knn))
print(classification_report(y_test,y_pred_knn))

#decision tree
dt = DecisionTreeClassifier(max_depth=6,random_state=42)
dt.fit(X_train_scale,y_train_resampled)
y_pred_dt=dt.predict(X_test_scale)
print("Decision Tree Model")
print(accuracy_score(y_test,y_pred_dt))
print(confusion_matrix(y_test,y_pred_dt))
print(classification_report(y_test,y_pred_dt))

#logical 
logreg = LogisticRegression()
logreg.fit(X_train_scale,y_train_resampled)
y_pred_logreg = logreg.predict(X_test_scale)
print("Logical Regression")
print(accuracy_score(y_test,y_pred_logreg))
print(confusion_matrix(y_test,y_pred_logreg))
print(classification_report(y_test,y_pred_logreg))

#random forest
rf = RandomForestClassifier(n_estimators = 25,random_state=42)
rf.fit(X_train_scale,y_train_resampled)
y_pred_rf=rf.predict(X_test_scale)
print("Random Forest Classifier")
print(accuracy_score(y_test,y_pred_rf))
print(confusion_matrix(y_test,y_pred_rf))
print(classification_report(y_test,y_pred_rf))


KNN Model
0.3
[[ 5 19]
 [ 2  4]]
              precision    recall  f1-score   support

           0       0.71      0.21      0.32        24
           1       0.17      0.67      0.28         6

    accuracy                           0.30        30
   macro avg       0.44      0.44      0.30        30
weighted avg       0.61      0.30      0.31        30

Decision Tree Model
0.6666666666666666
[[19  5]
 [ 5  1]]
              precision    recall  f1-score   support

           0       0.79      0.79      0.79        24
           1       0.17      0.17      0.17         6

    accuracy                           0.67        30
   macro avg       0.48      0.48      0.48        30
weighted avg       0.67      0.67      0.67        30

Logical Regression
0.6
[[16  8]
 [ 4  2]]
              precision    recall  f1-score   support

           0       0.80      0.67      0.73        24
           1       0.20      0.33      0.25         6

    accuracy                           0.60      

In [8]:
#baased with resample SMOTE
#hyperparameter tuning
kf=KFold(n_splits=5)
#knn
from sklearn.model_selection import GridSearchCV
param_grid_knn = {"n_neighbors" : [1,2,3,4,5,6,7,8,9], "weights" : ["uniform","distance"]}
grid_knn=GridSearchCV(KNeighborsClassifier(), param_grid_knn,cv=kf)
grid_knn.fit(X_train_resampled,y_train_resampled)
best_knn = grid_knn.best_estimator_
print(best_knn)  

    





KNeighborsClassifier(n_neighbors=2)


In [9]:
#dt
param_grid_dt = {"max_depth" : [2,4,6,8,10], "min_samples_split":[1,3,5,7,9,None],"criterion" : ["gni","entropy",None]}
grid_dt=GridSearchCV(DecisionTreeClassifier(random_state=42), param_grid_dt,cv=kf)
grid_dt.fit(X_train_resampled,y_train_resampled)
best_dt = grid_dt.best_estimator_
print(best_dt)     

DecisionTreeClassifier(criterion='entropy', max_depth=6, min_samples_split=7,
                       random_state=42)


C:\Users\khiny\anaconda3\envs\project1\lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning: 
350 fits failed out of a total of 450.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
150 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\khiny\anaconda3\envs\project1\lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\khiny\anaconda3\envs\project1\lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
  File "C:\Users\khiny\anaconda3\envs\project1\lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_const

In [10]:
knn = KNeighborsClassifier(n_neighbors=2)
knn.fit(X_train_scale,y_train_resampled)
y_pred_knn = knn.predict(X_test_scale)
print("KNN Model")
print(accuracy_score(y_test,y_pred_knn))
print(confusion_matrix(y_test,y_pred_knn))
print(classification_report(y_test,y_pred_knn))

#decision tree
dt = DecisionTreeClassifier(criterion='entropy', max_depth=6, min_samples_split=7,random_state=42)
dt.fit(X_train_scale,y_train_resampled)
y_pred_dt=dt.predict(X_test_scale)
print("Decision Tree Model")
print(accuracy_score(y_test,y_pred_dt))
print(confusion_matrix(y_test,y_pred_dt))
print(classification_report(y_test,y_pred_dt))

#random forest
rf = RandomForestClassifier(n_estimators = 10,random_state=42)
rf.fit(X_train_scale,y_train_resampled)
y_pred_rf=rf.predict(X_test_scale)
print("Random Forest Classifier")
print(accuracy_score(y_test,y_pred_rf))
print(confusion_matrix(y_test,y_pred_rf))
print(classification_report(y_test,y_pred_rf))

#logical 
logreg = LogisticRegression()
logreg.fit(X_train_scale,y_train_resampled)
y_pred_logreg = logreg.predict(X_test_scale)
print("Logistic Regression")
print(accuracy_score(y_test,y_pred_logreg))
print(confusion_matrix(y_test,y_pred_logreg))
print(classification_report(y_test,y_pred_logreg))




KNN Model
0.5666666666666667
[[17  7]
 [ 6  0]]
              precision    recall  f1-score   support

           0       0.74      0.71      0.72        24
           1       0.00      0.00      0.00         6

    accuracy                           0.57        30
   macro avg       0.37      0.35      0.36        30
weighted avg       0.59      0.57      0.58        30

Decision Tree Model
0.7
[[20  4]
 [ 5  1]]
              precision    recall  f1-score   support

           0       0.80      0.83      0.82        24
           1       0.20      0.17      0.18         6

    accuracy                           0.70        30
   macro avg       0.50      0.50      0.50        30
weighted avg       0.68      0.70      0.69        30

Random Forest Classifier
0.7666666666666667
[[22  2]
 [ 5  1]]
              precision    recall  f1-score   support

           0       0.81      0.92      0.86        24
           1       0.33      0.17      0.22         6

    accuracy                

In [11]:
#decision tree
dt = DecisionTreeClassifier(max_depth=6,random_state=42)
dt.fit(X_train_scale,y_train_resampled)
y_pred_dt=dt.predict(X_test_scale)
print("Decision Tree Model")
print(accuracy_score(y_test,y_pred_dt))
print(confusion_matrix(y_test,y_pred_dt))
print(classification_report(y_test,y_pred_dt))


Decision Tree Model
0.6666666666666666
[[19  5]
 [ 5  1]]
              precision    recall  f1-score   support

           0       0.79      0.79      0.79        24
           1       0.17      0.17      0.17         6

    accuracy                           0.67        30
   macro avg       0.48      0.48      0.48        30
weighted avg       0.67      0.67      0.67        30



In [14]:
X_train.columns

Index(['Pre_Knowledge_Data', 'Learning_hour', 'Time_duration',
       'discussion_rate', 'presentation_project_rate', 'assignment_rate',
       'participation', 'Gender_Female', 'Gender_Male',
       'Current_Situation_Employed', 'Current_Situation_None of the above',
       'Current_Situation_Student', 'Current_Situation_Unemployed',
       'Type_of_Internet_Home Wi-Fi', 'Type_of_Internet_Others',
       'Device_used_Not Own', 'Device_used_Own Computer',
       'Academic_career_Graduate (Degree holder)', 'Academic_career_Other',
       'Academic_career_Undergraduate Student',
       'Course_Wish_Join_Associate Data Analyst in SQL',
       'Course_Wish_Join_Data Analytics using Python',
       'Course_Wish_Join_Data Analytics using R',
       'Course_Wish_Join_Data Scientist using Python',
       'Course_Wish_Join_Other', 'Course_Wish_Join_Tableau', 'age_22.0',
       'age_23.0', 'age_24.0', 'age_25.0', 'age_26.0', 'age_27.0', 'age_28.0',
       'age_29.0', 'age_30.0', 'age_31.0', 'age

In [ ]:
test = {
    'Pre_Knowledge_Data': 2, 'Learning_hour': 4,'Time_duration': time_duration, 'discussion_rate': discussion,
    'presentation_project_rate': presentation_project, 'assignment_rate': assignment,
    'participation': participations, 'Gender_Female': 1, 'Gender_Male': 0,
    'Current_Situation_Employed': 1, 'Current_Situation_None of the above': 0,
    'Current_Situation_Student': 0, 'Current_Situation_Unemployed': 0,
    'Type_of_Internet_Home Wi-Fi': 1, 'Type_of_Internet_Others': 1,
    'Device_used_Not Own': 0, 'Device_used_Own Computer': 1,
    'Academic_career_Graduate (Degree holder)': 1, 'Academic_career_Other': 0,
    'Academic_career_Undergraduate Student': 0, 'Course_Wish_Join_Associate Data Analyst in SQL': 0,
    'Course_Wish_Join_Data Analytics using Python': 1, 'Course_Wish_Join_Data Analytics using R': 0,
    'Course_Wish_Join_Data Scientist using Python': 0, 'Course_Wish_Join_Other': 0,
    'Course_Wish_Join_Tableau': 0, 'age_22.0': 0, 'age_23.0': 0, 'age_24.0': 0,
    'age_25.0': 0, 'age_26.0': 0, 'age_27.0': 0, 'age_28.0': 0, 'age_29.0': 0,
    'age_30.0': 0, 'age_31.0': 0, 'age_32.0': 0, 'age_33.0': 0, 'age_34.0': 1,
    'age_35.0': 0, 'age_36.0': 0, 'age_37.0': 0, 'age_38.0': 0, 'age_39.0': 0,
    'age_41.0': 0, 'age_42.0': 0, 'age_43.0': 0, 'age_44.0': 0, 'age_45.0': 0,
    'age_46.0': 0, 'age_48.0': 0, 'Urbanization_Rural': 1, 'Urbanization_Urban': 0
    
}
test_df = pd.DataFrame([test])

#test_df_scaled = scaler.transform(test_df)

predicted_attendance = rf.predict(test_df)

print("Predicted Attendance Rate:", predicted_attendance, "%")